package oodj_assignment;

import java.awt.CardLayout;
import javax.swing.JButton;

/**
 * @author Wong Yee Chung
 * @author Chew chang wang
 */
public class AdminMenuGui extends javax.swing.JFrame {

	/**
	 * Creates new JFrame AdminMenuGui
	 */
	CardLayout cardlayout;
	public AdminMenuGui() {
		initComponents();
		setVisible(false);
		
		cardlayout = (CardLayout)(CardLayoutPanel.getLayout());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    SidePanel = new javax.swing.JPanel();
    AdminButton1 = new javax.swing.JButton();
    AdminButton2 = new javax.swing.JButton();
    AdminButton3 = new javax.swing.JButton();
    AdminButton4 = new javax.swing.JButton();
    AdminButton5 = new javax.swing.JButton();
    AdminExit = new javax.swing.JButton();
    MenuPanel = new javax.swing.JPanel();
    MenuLabel = new javax.swing.JLabel();
    CardLayoutPanel = new javax.swing.JPanel();
    AdminMenu_Course = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    jTextField3 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox<>();
    jLabel6 = new javax.swing.JLabel();
    jTextField4 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jTextField5 = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jScrollPane2 = new javax.swing.JScrollPane();
    jList2 = new javax.swing.JList<>();
    jScrollPane3 = new javax.swing.JScrollPane();
    jList3 = new javax.swing.JList<>();
    jScrollPane4 = new javax.swing.JScrollPane();
    jList4 = new javax.swing.JList<>();
    jScrollPane5 = new javax.swing.JScrollPane();
    jList5 = new javax.swing.JList<>();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    AdminMenu_Student = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    StudentList = new javax.swing.JLabel();
    scrollpane_stdTable = new javax.swing.JScrollPane();
    studentDetailsTable = new javax.swing.JTable();
    addStudentButton = new javax.swing.JButton();
    editStudentButton = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    AdminMenu_Lecture = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    LecturerList = new javax.swing.JLabel();
    scrollpane_lecTable = new javax.swing.JScrollPane();
    LecturerDetailsTable = new javax.swing.JTable();
    addLecturerButton = new javax.swing.JButton();
    editLecturerButton = new javax.swing.JButton();
    AdminMenu_log = new javax.swing.JPanel();
    ScrollPane_log = new javax.swing.JScrollPane();
    LogTable = new javax.swing.JTable();
    log = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    AdminMenu_Admin = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    AdminList = new javax.swing.JLabel();
    scrollpane_adTable = new javax.swing.JScrollPane();
    adminDetailsTable = new javax.swing.JTable();
    addAdminButton = new javax.swing.JButton();
    editAdminButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    SidePanel.setBackground(new java.awt.Color(0, 0, 51));
    SidePanel.setForeground(new java.awt.Color(255, 255, 255));

    AdminButton1.setBackground(new java.awt.Color(62, 128, 194));
    AdminButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
    AdminButton1.setForeground(new java.awt.Color(255, 255, 255));
    AdminButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_study_15px.png"))); // NOI18N
    AdminButton1.setText("Course and Module");
    AdminButton1.setToolTipText("Create and Modify Course and module");
    AdminButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    AdminButton1.setBorderPainted(false);
    AdminButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    AdminButton1.setMaximumSize(new java.awt.Dimension(81, 22));
    AdminButton1.setMinimumSize(new java.awt.Dimension(81, 22));
    AdminButton1.setPreferredSize(new java.awt.Dimension(81, 22));
    AdminButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AdminButton1ActionPerformed(evt);
      }
    });

    AdminButton2.setBackground(new java.awt.Color(0, 0, 51));
    AdminButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
    AdminButton2.setForeground(new java.awt.Color(255, 255, 255));
    AdminButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_student_male_15px.png"))); // NOI18N
    AdminButton2.setText("Student");
    AdminButton2.setToolTipText("Add and modify student account");
    AdminButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    AdminButton2.setBorderPainted(false);
    AdminButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    AdminButton2.setMaximumSize(new java.awt.Dimension(81, 22));
    AdminButton2.setMinimumSize(new java.awt.Dimension(81, 22));
    AdminButton2.setPreferredSize(new java.awt.Dimension(81, 22));
    AdminButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AdminButton2ActionPerformed(evt);
      }
    });

    AdminButton3.setBackground(new java.awt.Color(0, 0, 51));
    AdminButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
    AdminButton3.setForeground(new java.awt.Color(255, 255, 255));
    AdminButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_teacher_15px.png"))); // NOI18N
    AdminButton3.setText("Lecturer");
    AdminButton3.setToolTipText("Add and modify lecturer Account");
    AdminButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    AdminButton3.setBorderPainted(false);
    AdminButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    AdminButton3.setMaximumSize(new java.awt.Dimension(81, 22));
    AdminButton3.setMinimumSize(new java.awt.Dimension(81, 22));
    AdminButton3.setPreferredSize(new java.awt.Dimension(81, 22));
    AdminButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AdminButton3ActionPerformed(evt);
      }
    });

    AdminButton4.setBackground(new java.awt.Color(0, 0, 51));
    AdminButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
    AdminButton4.setForeground(new java.awt.Color(255, 255, 255));
    AdminButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_log_15px.png"))); // NOI18N
    AdminButton4.setText("Log");
    AdminButton4.setToolTipText("Generate and view log File");
    AdminButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    AdminButton4.setBorderPainted(false);
    AdminButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    AdminButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AdminButton4ActionPerformed(evt);
      }
    });

    AdminButton5.setBackground(new java.awt.Color(0, 0, 51));
    AdminButton5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
    AdminButton5.setForeground(new java.awt.Color(255, 255, 255));
    AdminButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_admin_settings_male_15px.png"))); // NOI18N
    AdminButton5.setText("Administrator");
    AdminButton5.setToolTipText("Add and modify Administrator");
    AdminButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    AdminButton5.setBorderPainted(false);
    AdminButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    AdminButton5.setMaximumSize(new java.awt.Dimension(81, 22));
    AdminButton5.setMinimumSize(new java.awt.Dimension(81, 22));
    AdminButton5.setPreferredSize(new java.awt.Dimension(81, 22));
    AdminButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AdminButton5ActionPerformed(evt);
      }
    });

    AdminExit.setBackground(new java.awt.Color(0, 0, 51));
    AdminExit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
    AdminExit.setForeground(new java.awt.Color(255, 255, 255));
    AdminExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_exit_15px.png"))); // NOI18N
    AdminExit.setText("Exit");
    AdminExit.setToolTipText("Exit");
    AdminExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    AdminExit.setBorderPainted(false);
    AdminExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    AdminExit.setMaximumSize(new java.awt.Dimension(81, 22));
    AdminExit.setMinimumSize(new java.awt.Dimension(81, 22));
    AdminExit.setPreferredSize(new java.awt.Dimension(81, 22));
    AdminExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AdminExitActionPerformed(evt);
      }
    });

    MenuPanel.setBackground(new java.awt.Color(0, 73, 102));

    MenuLabel.setBackground(new java.awt.Color(255, 255, 255));
    MenuLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
    MenuLabel.setForeground(new java.awt.Color(255, 255, 255));
    MenuLabel.setText("MENU");

    javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
    MenuPanel.setLayout(MenuPanelLayout);
    MenuPanelLayout.setHorizontalGroup(
      MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MenuPanelLayout.createSequentialGroup()
        .addGap(47, 47, 47)
        .addComponent(MenuLabel)
        .addContainerGap(51, Short.MAX_VALUE))
    );
    MenuPanelLayout.setVerticalGroup(
      MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MenuPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(MenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
    SidePanel.setLayout(SidePanelLayout);
    SidePanelLayout.setHorizontalGroup(
      SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(AdminButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(AdminButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(AdminButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(AdminButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(SidePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(AdminExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addComponent(AdminButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    SidePanelLayout.setVerticalGroup(
      SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(SidePanelLayout.createSequentialGroup()
        .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(84, 84, 84)
        .addComponent(AdminButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(AdminButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(AdminButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(AdminButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(AdminButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(AdminExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

    CardLayoutPanel.setLayout(new java.awt.CardLayout());

    AdminMenu_Course.setBackground(new java.awt.Color(204, 253, 255));

    jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
    jLabel1.setText("Course and  Module");

    jLabel2.setText("Course Name");

    jTextField1.setColumns(10);

    jLabel3.setText("Level");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", " " }));

    jLabel4.setText("Year");

    jTextField3.setColumns(5);

    jLabel5.setText("Month");

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabel6.setText("Short Course Name");

    jTextField4.setColumns(10);

    jLabel7.setText("Module Name");

    jTextField2.setColumns(10);

    jLabel8.setText("Module Short Name");
    jLabel8.setToolTipText("");

    jTextField5.setColumns(5);

    jList1.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(jList1);

    jList2.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane2.setViewportView(jList2);

    jList3.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane3.setViewportView(jList3);

    jList4.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane4.setViewportView(jList4);

    jList5.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane5.setViewportView(jList5);

    jLabel9.setText("jLabel9");

    jLabel10.setText("jLabel10");

    jLabel11.setText("jLabel11");

    jLabel12.setText("jLabel12");

    jLabel13.setText("jLabel13");

    jButton3.setText("Add");

    jButton4.setText("Edit");

    jButton5.setText("Delete");

    javax.swing.GroupLayout AdminMenu_CourseLayout = new javax.swing.GroupLayout(AdminMenu_Course);
    AdminMenu_Course.setLayout(AdminMenu_CourseLayout);
    AdminMenu_CourseLayout.setHorizontalGroup(
      AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AdminMenu_CourseLayout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel10))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel11))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel12))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel13)
          .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(AdminMenu_CourseLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addGroup(AdminMenu_CourseLayout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(AdminMenu_CourseLayout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(AdminMenu_CourseLayout.createSequentialGroup()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel9)
          .addGroup(AdminMenu_CourseLayout.createSequentialGroup()
            .addComponent(jButton3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton5)))
        .addContainerGap(12, Short.MAX_VALUE))
    );
    AdminMenu_CourseLayout.setVerticalGroup(
      AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AdminMenu_CourseLayout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4)
          .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6)
          .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8)
          .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton3)
          .addComponent(jButton4)
          .addComponent(jButton5))
        .addGap(41, 41, 41)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(jLabel10)
          .addComponent(jLabel11)
          .addComponent(jLabel12)
          .addComponent(jLabel13))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(AdminMenu_CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
          .addComponent(jScrollPane2)
          .addComponent(jScrollPane3)
          .addComponent(jScrollPane4)
          .addComponent(jScrollPane5))
        .addContainerGap())
    );

    CardLayoutPanel.add(AdminMenu_Course, "1");

    AdminMenu_Student.setBackground(new java.awt.Color(255, 255, 255));

    jPanel1.setBackground(new java.awt.Color(204, 253, 255));
    jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    StudentList.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
    StudentList.setText("Students List");

    scrollpane_stdTable.setBackground(new java.awt.Color(204, 253, 255));
    scrollpane_stdTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentDetailsTable.setAutoCreateRowSorter(true);
    studentDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null}
      },
      new String [] {
        "ID", "Name", "Intake", "Email"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    studentDetailsTable.setToolTipText("");
    studentDetailsTable.setCellSelectionEnabled(true);
    studentDetailsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    studentDetailsTable.setName(""); // NOI18N
    studentDetailsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    studentDetailsTable.setShowGrid(true);
    studentDetailsTable.getTableHeader().setResizingAllowed(false);
    studentDetailsTable.getTableHeader().setReorderingAllowed(false);
    scrollpane_stdTable.setViewportView(studentDetailsTable);

    addStudentButton.setText("Add New Student");
    addStudentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    editStudentButton.setText("Edit Student Details");
    editStudentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jButton2.setText("Generate Students List");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(StudentList, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
              .addComponent(addStudentButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(editStudentButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jButton2))
            .addComponent(scrollpane_stdTable, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(StudentList, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(addStudentButton)
          .addComponent(editStudentButton)
          .addComponent(jButton2))
        .addGap(63, 63, 63)
        .addComponent(scrollpane_stdTable, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout AdminMenu_StudentLayout = new javax.swing.GroupLayout(AdminMenu_Student);
    AdminMenu_Student.setLayout(AdminMenu_StudentLayout);
    AdminMenu_StudentLayout.setHorizontalGroup(
      AdminMenu_StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AdminMenu_StudentLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    AdminMenu_StudentLayout.setVerticalGroup(
      AdminMenu_StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jPanel1.getAccessibleContext().setAccessibleName("");
    jPanel1.getAccessibleContext().setAccessibleDescription("");

    CardLayoutPanel.add(AdminMenu_Student, "2");

    jPanel2.setBackground(new java.awt.Color(204, 253, 255));
    jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    LecturerList.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
    LecturerList.setText("Lecturers List");

    scrollpane_lecTable.setBackground(new java.awt.Color(204, 253, 255));
    scrollpane_lecTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    LecturerDetailsTable.setAutoCreateRowSorter(true);
    LecturerDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null}
      },
      new String [] {
        "ID", "Name", "Email", "Module", "Intake"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    LecturerDetailsTable.setToolTipText("");
    LecturerDetailsTable.setCellSelectionEnabled(true);
    LecturerDetailsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    LecturerDetailsTable.setName(""); // NOI18N
    LecturerDetailsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    LecturerDetailsTable.setShowGrid(true);
    LecturerDetailsTable.getTableHeader().setResizingAllowed(false);
    LecturerDetailsTable.getTableHeader().setReorderingAllowed(false);
    scrollpane_lecTable.setViewportView(LecturerDetailsTable);

    addLecturerButton.setText("Add New Lecturer");
    addLecturerButton.setToolTipText("");
    addLecturerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    editLecturerButton.setText("Edit Lecturer Details");
    editLecturerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
              .addComponent(addLecturerButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(editLecturerButton))
            .addComponent(scrollpane_lecTable, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(LecturerList))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(LecturerList, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(addLecturerButton)
          .addComponent(editLecturerButton))
        .addGap(18, 18, 18)
        .addComponent(scrollpane_lecTable, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout AdminMenu_LectureLayout = new javax.swing.GroupLayout(AdminMenu_Lecture);
    AdminMenu_Lecture.setLayout(AdminMenu_LectureLayout);
    AdminMenu_LectureLayout.setHorizontalGroup(
      AdminMenu_LectureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AdminMenu_LectureLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    AdminMenu_LectureLayout.setVerticalGroup(
      AdminMenu_LectureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    CardLayoutPanel.add(AdminMenu_Lecture, "3");

    AdminMenu_log.setBackground(new java.awt.Color(204, 253, 255));

    ScrollPane_log.setBackground(new java.awt.Color(204, 253, 255));
    ScrollPane_log.setForeground(new java.awt.Color(204, 253, 255));

    LogTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "ID", "Name", "Login time", "Login time"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    LogTable.setRowSelectionAllowed(false);
    LogTable.setShowGrid(true);
    LogTable.getTableHeader().setResizingAllowed(false);
    LogTable.getTableHeader().setReorderingAllowed(false);
    ScrollPane_log.setViewportView(LogTable);

    log.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
    log.setText("User Log");

    jButton1.setText("Generate Log Report");

    javax.swing.GroupLayout AdminMenu_logLayout = new javax.swing.GroupLayout(AdminMenu_log);
    AdminMenu_log.setLayout(AdminMenu_logLayout);
    AdminMenu_logLayout.setHorizontalGroup(
      AdminMenu_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ScrollPane_log, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
      .addGroup(AdminMenu_logLayout.createSequentialGroup()
        .addGroup(AdminMenu_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(AdminMenu_logLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(AdminMenu_logLayout.createSequentialGroup()
            .addGap(213, 213, 213)
            .addComponent(jButton1)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    AdminMenu_logLayout.setVerticalGroup(
      AdminMenu_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AdminMenu_logLayout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addComponent(log)
        .addGap(58, 58, 58)
        .addComponent(ScrollPane_log, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton1)
        .addContainerGap(94, Short.MAX_VALUE))
    );

    CardLayoutPanel.add(AdminMenu_log, "4");

    AdminMenu_Admin.setBackground(new java.awt.Color(255, 255, 255));

    jPanel3.setBackground(new java.awt.Color(204, 253, 255));
    jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    AdminList.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
    AdminList.setText("Administrators List");

    scrollpane_adTable.setBackground(new java.awt.Color(204, 253, 255));
    scrollpane_adTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    adminDetailsTable.setAutoCreateRowSorter(true);
    adminDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null}
      },
      new String [] {
        "ID", "Name"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    adminDetailsTable.setToolTipText("");
    adminDetailsTable.setCellSelectionEnabled(true);
    adminDetailsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    adminDetailsTable.setName(""); // NOI18N
    adminDetailsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    adminDetailsTable.setShowGrid(true);
    adminDetailsTable.getTableHeader().setResizingAllowed(false);
    adminDetailsTable.getTableHeader().setReorderingAllowed(false);
    scrollpane_adTable.setViewportView(adminDetailsTable);

    addAdminButton.setText("Add New Administrator");
    addAdminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    editAdminButton1.setText("Edit Administrator Details");
    editAdminButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
              .addComponent(addAdminButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(editAdminButton1))
            .addComponent(scrollpane_adTable, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(AdminList))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(AdminList, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(addAdminButton)
          .addComponent(editAdminButton1))
        .addGap(18, 18, 18)
        .addComponent(scrollpane_adTable, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout AdminMenu_AdminLayout = new javax.swing.GroupLayout(AdminMenu_Admin);
    AdminMenu_Admin.setLayout(AdminMenu_AdminLayout);
    AdminMenu_AdminLayout.setHorizontalGroup(
      AdminMenu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AdminMenu_AdminLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    AdminMenu_AdminLayout.setVerticalGroup(
      AdminMenu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    CardLayoutPanel.add(AdminMenu_Admin, "5");

    getContentPane().add(CardLayoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 580, 510));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void AdminExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminExitActionPerformed
    // TODO add your handling code here:
		setVisible(false);
		Grading_System.lg.setVisible(true);
  }//GEN-LAST:event_AdminExitActionPerformed

  private void AdminButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButton1ActionPerformed
    // TODO add your handling code here:
		SetColor(AdminButton1);
		ResetColor(AdminButton2);
		ResetColor(AdminButton3);
		ResetColor(AdminButton4);
		ResetColor(AdminButton5);
		
		
		cardlayout.show(CardLayoutPanel, "1");
		
		
		
  }//GEN-LAST:event_AdminButton1ActionPerformed

  private void AdminButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButton2ActionPerformed
    // TODO add your handling code here:
		ResetColor(AdminButton1);
		SetColor(AdminButton2);
		ResetColor(AdminButton3);
		ResetColor(AdminButton4);
		ResetColor(AdminButton5);
		
		cardlayout.show(CardLayoutPanel, "2");
		
		
		
		
  }//GEN-LAST:event_AdminButton2ActionPerformed

  private void AdminButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButton3ActionPerformed
    // TODO add your handling code here:
		ResetColor(AdminButton1);
		ResetColor(AdminButton2);
		SetColor(AdminButton3);
		ResetColor(AdminButton4);
		ResetColor(AdminButton5);
		
		cardlayout.show(CardLayoutPanel, "3");
		
		
		
		
  }//GEN-LAST:event_AdminButton3ActionPerformed

  private void AdminButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButton4ActionPerformed
    // TODO add your handling code here:
		ResetColor(AdminButton1);
		ResetColor(AdminButton2);
		ResetColor(AdminButton3);
		SetColor(AdminButton4);
		ResetColor(AdminButton5);
		
		cardlayout.show(CardLayoutPanel, "4");
		
		
		
		
  }//GEN-LAST:event_AdminButton4ActionPerformed

  private void AdminButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButton5ActionPerformed
    // TODO add your handling code here:
		ResetColor(AdminButton1);
		ResetColor(AdminButton2);
		ResetColor(AdminButton3);
		ResetColor(AdminButton4);
		SetColor(AdminButton5);
		
		cardlayout.show(CardLayoutPanel, "5");
		
		
		
		
  }//GEN-LAST:event_AdminButton5ActionPerformed

	
//	public static void main(String args[]) {
//		//		/* Set the Nimbus look and feel */
//		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Windows".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(AdminMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(AdminMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(AdminMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(AdminMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		}
//		//</editor-fold>
//
//
//
//
//		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new AdminMenuGui().setVisible(true);
//			}
//		});
//	}
	
	
	
	public void SetColor (JButton button){
		button.setBackground(new java.awt.Color(62, 128, 194));
	}
	
	public void ResetColor (JButton button){
		button.setBackground(new java.awt.Color(0,0,51));
	}
	
	
	
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton AdminButton1;
  private javax.swing.JButton AdminButton2;
  private javax.swing.JButton AdminButton3;
  private javax.swing.JButton AdminButton4;
  private javax.swing.JButton AdminButton5;
  private javax.swing.JButton AdminExit;
  private javax.swing.JLabel AdminList;
  private javax.swing.JPanel AdminMenu_Admin;
  private javax.swing.JPanel AdminMenu_Course;
  private javax.swing.JPanel AdminMenu_Lecture;
  private javax.swing.JPanel AdminMenu_Student;
  private javax.swing.JPanel AdminMenu_log;
  private javax.swing.JPanel CardLayoutPanel;
  private javax.swing.JTable LecturerDetailsTable;
  private javax.swing.JLabel LecturerList;
  private javax.swing.JTable LogTable;
  private javax.swing.JLabel MenuLabel;
  private javax.swing.JPanel MenuPanel;
  private javax.swing.JScrollPane ScrollPane_log;
  private javax.swing.JPanel SidePanel;
  private javax.swing.JLabel StudentList;
  private javax.swing.JButton addAdminButton;
  private javax.swing.JButton addLecturerButton;
  private javax.swing.JButton addStudentButton;
  private javax.swing.JTable adminDetailsTable;
  private javax.swing.JButton editAdminButton1;
  private javax.swing.JButton editLecturerButton;
  private javax.swing.JButton editStudentButton;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JList<String> jList1;
  private javax.swing.JList<String> jList2;
  private javax.swing.JList<String> jList3;
  private javax.swing.JList<String> jList4;
  private javax.swing.JList<String> jList5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JLabel log;
  private javax.swing.JScrollPane scrollpane_adTable;
  private javax.swing.JScrollPane scrollpane_lecTable;
  private javax.swing.JScrollPane scrollpane_stdTable;
  private javax.swing.JTable studentDetailsTable;
  // End of variables declaration//GEN-END:variables
}

